name: Build and Push Docker Image


on:
  push:
    branches:
      - Project-JA-3


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://hub.docker.com
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      # - name: Build and Push Docker Image
      #   run: |
        
      #     docker buildx create --use
      #     docker buildx build --platform linux/amd64,linux/arm64 -t your-image:latest .
      #     docker push your-image:latest